**1 Список чисел**

На вход программе подается одно число n. Напишите программу, которая выводит список [1, 2, 3, ..., n].

In [ ]:
# Пример ввода
10

# Пример вывода
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**2 Список букв**

На вход программе подается одно число n, при этом 1≤n≤26. Напишите программу, которая выводит список, состоящий из n букв английского алфавита ['a', 'b', 'c', ...] в нижнем регистре.

In [ ]:
syms = 'abcdefghijklmnopqrstuvwxyz'

In [ ]:
# Пример ввода
10

# Пример вывода
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

**3 Сумма минимума и максимума**

Дополните приведенный ниже код, так чтобы он вывел сумму минимального и максимального элементов списка numbers

In [ ]:
#Правильный ответ - 107.4

numbers = [58.41, 94.9, 68.75, 91.83, 66.19, 12.5, 23.27, 79.7, 83.71, 13.67, 55.29, 67.34, 75.57, 38.5, 35.33, 23.1, 50.76, 21.4, 33.76, 30.13, 90.11, 13.07, 92.74, 91.9, 37.34]

**4 Среднее арифметическое**

Дополните приведенный ниже код так, чтобы он вывел среднее арифметическое элементов списка evens.

In [ ]:
# Правильный ответ - 49.605999999999995

evens = [65.03, 28.35, 32.93, 15.15, 98.19, 56.37, 27.47, 32.39, 23.28, 17.06, 55.88, 45.78, 73.44, 25.91, 43.5, 75.44, 67.23, 50.76, 19.48, 66.13, 54.38, 69.42, 87.82, 27.61, 81.15]

**5 Всё везде и сразу**

Дополните приведенный код, чтобы он:

* Вывел длину списка;
* Вывел последний элемент списка;
* Вывел список в обратном порядке (вспоминаем срезы);
* Вывел YES, если список содержит числа 5 и 17, и NO в противном случае;
* Вывел список с удаленными первым и последним элементами.

Каждый вывод осуществлять с новой строки.

In [ ]:
numbers = [2, 6, 3, 14, 10, 4, 11, 16, 12, 5, 4, 16, 1, 0, 8, 16, 10, 10, 8, 5, 1, 11, 10, 10, 12, 0, 0, 6, 14, 8, 2, 12, 14, 5, 6, 12, 1, 2, 10, 14, 9, 1, 15, 1, 2, 14, 16, 6, 7, 5]

In [ ]:
# Правильный результат:

50
5
[5, 7, 6, 16, 14, 2, 1, 15, 1, 9, 14, 10, 2, 1, 12, 6, 5, 14, 12, 2, 8, 14, 6, 0, 0, 12, 10, 10, 11, 1, 5, 8, 10, 10, 16, 8, 0, 1, 16, 4, 5, 12, 16, 11, 4, 10, 14, 3, 6, 2]
NO
[6, 3, 14, 10, 4, 11, 16, 12, 5, 4, 16, 1, 0, 8, 16, 10, 10, 8, 5, 1, 11, 10, 10, 12, 0, 0, 6, 14, 8, 2, 12, 14, 5, 6, 12, 1, 2, 10, 14, 9, 1, 15, 1, 2, 14, 16, 6, 7]

**6 Список строк**

На вход программе подается натуральное число n, а затем n строк. Напишите программу, которая создает из указанных строк список и выводит его.

**Формат входных данных** На вход программе подаются натуральное число n, а затем n строк, каждая на отдельной строке.

In [ ]:
# Пример ввода
5
C#
C++
C
Python
F#

# Пример вывода
['C#', 'C++', 'C', 'Python', 'F#']

**7 Список делителей**

На вход программе подается натуральное число n. Напишите программу, которая создает список, состоящий из делителей введенного числа.

In [ ]:
# Пример ввода
36

# Пример вывода
[1, 2, 3, 4, 6, 9, 12, 18, 36]

**8 Суммы двух**

На вход программе подается натуральное число n, где n≥2. Затем поступают n целых чисел. Напишите программу, которая создает из указанных чисел список, состоящий из сумм соседних чисел (первого и второго, второго и третьего, третьего и четвертого и т.д.).

Формат входных данных
На вход программе подаются натуральное число n, а затем n целых чисел, каждое на отдельной строке.

In [ ]:
# Пример ввода
5
1
2
3
4
5

# Пример вывода
[3, 5, 7, 9]

**9 k-ая буква слова (задача немного сложнее остальных)**

На вход программе подается натуральное число n и n строк, а затем число k. Напишите программу, которая выводит k-ую букву из введенных строк на одной строке без пробелов.

**Формат входных данных** На вход программе подается натуральное число n,  далее n строк, каждая на отдельной строке. В конце вводится натуральное число k – номер буквы (нумерация начинается с единицы).

**Примечание.** Если некоторые строки слишком короткие, и в них нет символа с заданным номером, то такие строки при выводе нужно игнорировать.

In [ ]:
# Пример ввода

5           # Ввели n - количество строк
abcdef      # Далее идут n строк (тут 5)
bcdefg
cdefgh
defghi
efghij
2           # Вводим номер буквы

# Пример вывода
bcdef       # Все вторые буквы строк

# Пример ввода

5
aaaaa
bbbbb
ccccc
ddddd
eee
5

# Пример вывода
abcd

**10 Без дубликатов**

На вход программе подается натуральное число n, а затем n строк. Напишите программу, которая выводит только уникальные строки, в том же порядке, в котором они были введены.

In [ ]:
#пример ввода

5 3 1 7 10 2

#ожидаемый вывод

+++++
+++
+
+++++++
++++++++++
++

**11 Диаграмма**

На вход программе подается строка текста, содержащая целые числа. Напишите программу, которая по заданным числам строит столбчатую диаграмму.

In [ ]:
#пример ввода

3 5 7 1


#ожидаемый вывод

+++
+++++
+++++++
+

**12 Добавь разделитель**

На вход программе подается строка текста и строка-разделитель. Напишите программу, которая вставляет указанный разделитель между каждым символом введенной строки текста.

**Формат ввода** На вход программе подается строка текста и строка-разделитель, каждая на отдельной строке

In [ ]:
#пример ввода

qwerty and password
**

#ожидаемый вывод

q**w**e**r**t**y** **a**n**d** **p**a**s**s**w**o**r**d

**13 Отрицательные, нули и положительные (задача немного сложнее остальных)**

На вход программе подается строка, состоящая из чисел, разделенных пробелом. Напишите программу, которая сначала выводит все отрицательные числа, затем нули, а затем все положительные числа, каждое на отдельной строке. Числа должны быть выведены в том же порядке, в котором они были введены.

In [ ]:
#пример ввода

3 -4 1 0 -1 0 -2

#ожидаемый вывод
-4
-1
-2
0
0
3
1

**14 Более одного экземпляра (задача немного сложнее остальных)**

На вход программе подается строка, содержащая целые неотрицательные числа, разделенные пробелом. Напишите программу, которая выводит те числа, которые встречаются в данной последовательности более одного раза.

In [ ]:
#пример ввода

2 1 3 4 2 3 5 7

#ожидаемый вывод

2 3

**15 Количество артиклей**

Вам дана string, содержащая английский текст. Слова текста разделены символом пробела. Напишите программу, которая подсчитывает общее количество артиклей: 'a', 'an', 'the'. **Артикли могут начинаться с заглавной буквы.**

In [ ]:
#правильный ответ - 7

string = 'William Shakespeare was born in the town of Stratford, England, in the year 1564. When he was A young man, Shakespeare moved to the city of London, where he began writing plays. His plays were soon very successful, and were enjoyed both by the common people of London and also by the rich and famous. In addition to his plays, Shakespeare wrote many short poems and a few longer poems. Like his plays, these poems are still famous today.'

**Задача 16. Корректный IP-адрес (задача сложнее остальных)**

IP-адрес записывается в виде четырёх десятичных чисел (октетов) со значением от 0 до 255 (включительно), разделённых точками, например, 192.168.1.2.
Напишите программу для проверки корректности IP-адреса: все ли октеты в IP-адресе – числа со значением от 0 до 255.

На вход программе подается строка в формате x.x.x.x, где x – непустой набор символов 0-9, a-z. Программа должна вывести True если введенная строка – корректный IP-адрес и False в противном случае.

**Примечание.** Ведущие нули следует игнорировать:

* 0001 = 1
* 006 = 6
* 0213 = 213
* 0000 = 0
* 00345 = 345

In [ ]:
# Примеры ввода / вывода:

10.01.1.1
True

10.1.1.a
False

10.1.1.260
False

10.0023.0123.0000015
True

**17 Домашний Google search (задача ощутимо сложнее остальных)**

На вход программе подается натуральное число n, затем n строк, затем число
k — количество поисковых запросов, затем k строк — поисковые запросы. Напишите программу, которая выводит все введенные строки, в которых встречаются одновременно все поисковые запросы.

**Формат входных данных** На вход программе подаются натуральное число n — количество строк, затем сами строки в указанном количестве, затем число k, затем сами поисковые запросы.

In [ ]:
#пример ввода

6                                               # Получаем число n - число строк для поиска В НИХ
Язык Python прекрасен                           # Далее получаем n строк (тут 6)
C# - отличный язык программирования
Colab - отличная платформа
PASSW qwerty FOREVER навсегда! gaga
язык Python появился 20 февраля 1991
пчела passw лучшая как всегдаgaga qwerty
4                                               # Получаем число k - количество поисковых запросов
passw                                         # Далее получаем k строк (тут 4)
Всегда
gaga
qwerty

#ожидаемый вывод
PASSW qwerty FOREVER навсегда! gaga
пчела passw лучшая как всегдаgaga qwerty